LEXICON_START: dict[str, str] = {
    'ru': "<i> 🎉 Добро пожаловать в Safirlogistics – вашему надежному партнеру в выполнении заказов! 😊{}\n\n"
          "Мы специализируемся на услугах по выполнению заказов для крупнейших маркетплейсов. \n"
          "Наш центр расположен в Лас-Вегасе, всего в 1.5 мили от склада Amazon.\n\n</i>"
          "<b>Наши услуги включают:\n</b>"
          "<i>📌 Прием и хранение товаров\n"
          "📌 Комплектация и упаковка заказов\n"
          "📌 Отправка и логистика\n"
          "📌 Обработка возвратов\n\n</i>"
          "<b>Почему выбирают нас?🤔\n</b>"
          "<i>💡Высокое качество обслуживания\n"
          "💡Быстрая и удобная поддержка\n"
          "💡Удобные способы оплаты\n"
          "💡Профессионализм и опыт\n"
          "💡Современные технологии управления\n\n"
          "Мы готовы стать вашим ключевым партнером в управлении логистикой. Свяжитесь с нами сегодня! 🤝</i>",
    'en': "<i> 🎉 Welcome to Safirlogistics – your reliable partner in order fulfillment! 😊{}\n\n"
            "We specialize in order fulfillment services for major marketplaces. \n"
            "Our center is located in Las Vegas, just 1.5 miles from the Amazon warehouse.\n\n</i>"
            "<b>Our services include:\n</b>"
            "<i>📌 Receiving and storing goods\n"
            "📌 Order picking and packing\n"
            "📌 Shipping and logistics\n"
            "📌 Returns processing\n\n</i>"
            "<b>Why choose us?🤔\n</b>"
            "<i>💡High quality service\n"
            "💡Fast and convenient support\n"
            "💡Convenient payment methods\n"
            "💡Professionalism and experience\n"
            "💡Modern management technologies\n\n"
            "We are ready to become your key partner in logistics management. Contact us today! 🤝</i>",
    'uk': "<i> 🎉 Ласкаво просимо до Safirlogistics – вашого надійного партнера в виконанні замовлень! 😊{}\n\n"
            "Ми спеціалізуємося на послугах з виконання замовлень для найбільших маркетплейсів. \n"
            "Наш центр розташований в Лас-Вегасі, всього в 1.5 мили від складу Amazon.\n\n</i>"
            "<b>Наші послуги включають:\n</b>"
            "<i>📌 Прийом та зберігання товарів\n"
            "📌 Комплектація та упаковка замовлень\n"
            "📌 Відправка та логістика\n"
            "📌 Обробка повернень\n\n</i>"
            "<b>Чому обирають нас?🤔\n</b>"
            "<i>💡Висока якість обслуговування\n"
            "💡Швидка та зручна підтримка\n"
            "💡Зручні способи оплати\n"
            "💡Професіоналізм та досвід\n"
            "💡Сучасні технології управління\n\n"
            "Ми готові стати вашим ключовим партнером в управлінні логістикою. Зв'яжіться з нами сьогодні! 🤝</i>",
}
